name: Deploy to Railway Prod

on:
  pull_request:
    types:
      - closed
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Merge request to master
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
        run: |
          git checkout master
          git merge ${{ github.head_ref }}
          git push origin master

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install packages
        run: npm install

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PROD_TOKEN }}
